---
deployment:
  tasks:
    - export REPOPATH=/home/thelessone/repositories/the_lessoner_card/*
    - export SITEPATH=/home/thelessone/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH